### ISSUE TITLE
 Implementation & structure

### ISSUE THREAD

**Issue by Suntrie** [mishkowsky/JavaClass#1]
1. <s>В java принято орагнизовывать классы в [пакеты](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html). Понятно, что у Вас скорее всего нет никакого сайта. В этом случае можно его придумать или взять название орагнизации, в рамках которой делается проект. Например, org.spbstu.your_surname. Каждый файл исходного кода должен находится в структуре папок, соответствующей названию его пакета. Например, если файл исходного кода озаглавлен директивой package com.mycompany.myname, то этот файл должен располагаться по пути com/mycompany/myname относительно папки с исходным кодом внутри проекта. В maven проектах принято использовать groupId в качестве префикса для всех пакетов проекта. Соответственно, к groupId применяются все те же правила именования, что и к пакетам. Про проблемы с дефолтным пакетом можно почитать, например, [здесь](https://stackoverflow.com/questions/7849421/is-the-use-of-javas-default-package-a-bad-practice)</s>

<s>2. Как будут работать классы с дефолтной областью видимости и публичными методами? Классы, которые мы разрабатываем, должны быть доступны программистам-клиентам в качестве библиотечных (быть public);</s> **Upd.** Выделение интерфейса - хорошая идея с точки зрения стиля;

<s>3. Возвращать коллекции принято через использование интерфейсов, а не тех реализаций, которые используются внутри класса/ метода (используя интерфейсы, Вы "подписываете обязательство" на то, что возвращаемая коллекция должна реализовывать только часть методов, которыми обладает коллекция, на данный момент реально используемая в реализации - и внешние "клиенты", которым Вы её вернёте, могут рассчитывать только на эти методы. Таким образом, внутри своего метода Вы потом можете менять коллекцию, например, на другие виды, удовлетворяющие интерфейсу - а в использующем коде при этом менять ничего не придётся). Поля также обычно объявляются с применением интерфейсов;</s>

<s>4. Чем отличается блок динамической инициализации просто от конструктора? Кто из них Вам на самом деле нужен?</s>

<s>5. Что-то пошло не так с чекерами (пока возможны варианты некорректного задания параметров + задания параметров с отсутствием проверок, которое по итогу может привести к возникновению NullPointerException);</s> <s>**Upd.** Просьба быть готовым на следующем занятии обсудить разницу checked/unchecked исключений и мотивировать сделанный выбор (как вариант - можно ответным сообщением здесь);</s>

<s>6. Для методов типа add/delete стоит добавить возвращаемое значение (например, boolean, или предшествующую версию объекта, лежавшего под этим ключом; можно посмотреть, например, описание методов интерфейса Map (правой кнопкой мыши по Map, go to-> Declaration);</s>

<s>7. У специальных типов возвращаемых значений null/ false несколько иная логика применения, чем у выбрасывания исключений. В первом случае - выполнение операции логически невозможно, но программа должна обрабатывать такую ситуацию штатными средствами. Например, товар под кодом не лежал, но код, в принципе, допустимый. Во втором - все (за исключением специальных случаев) должно падать (возможно, с дополнительной обработкой типа логирования/ формирования кода ошибки в catch).</s> Будьте, пожалуйста, готовы со мной обсудить при сдаче чем отличаются checked/ unchecked исключения (получается, это уже было);

<s>8. [new line](https://www.baeldung.com/java-string-newline);</s>

<s>9. Текстовые константы принято выносить в начало определения класса (как константы) с модификаторами public static final String (проще изменять при версионировании кода); **Upd.** Почти, но не совсем. Конвенция именования констант немного отличается от именования переменных;</s>

<s>10. Для именования переменных в Java применяется lowerCamelCase;</s>

<s>11. Проверьте, пожалуйста, чтобы покрытие тестами в Вашем коде было 80%+.</s>

**Comment by Suntrie** [comment]
1. Пока структура папок не соответствует [дефолтному лейауту Maven](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) (и средствами чистого Maven он не соберётся) 
<img width="1440" alt="Screenshot 2021-02-20 at 23 44 31" src="https://user-images.githubusercontent.com/31803067/108608109-bf524400-73d5-11eb-8544-712680756c9e.png">

**Upd.** Всё ещё актуальная проблема и это мажорный комментарий. Что такое Maven, зачем он нужен и что такое фазы жизненного цикла мы с Вами должны были обсуждать в первом семестре. Также скидывала доку с пояснениями. Если остаются вопросы - пишите конкретные, пожалуйста. Сейчас понять, что пошло не так, можно выбрав Maven в качестве правой вкладки и запустив package. *.jar архив в появившейся папке target можно любым архиватором попробовать открыть, и увидеть, что там не будет файлов с расширением .class, которые выполняются Java машиной. Для второй работы этот опыт также будет валиден, там jar-файлы с помощью java надо будет запускать.

<s>2. Удалите, пожалуйста, папку target из-под контроля git и с гита тоже (git rm). Бинарные файлы являются производными от файлов исходного кода и не так уж мало весят, поэтому их, как правило, не выкладывают;</s>

<s>3. Как правило, названия файла совпадает с названием класса верхнего уровня (тесты);</s>

<s>4. Создавать объект класса PriceList, передавая в него неподконтрольный нам Map, в котором кто-то, кто тоже имеет на него ссылку, может менять руками в обход методов всё, что угодно - это точно хорошая идея?</s> **Upd.** С общей логикой согласна, но базовый Map хорош в том, что в нём невозможны дубликаты кодов...

5. Поясните, пожалуйста, почему для реализации PriceList hashCode был выбран именно Objects.hash? (вроде, есть более простые варианты);

<s>6. private int price; - насколько большие цены Вы сможете так хранить? "Цена представляется в рублях и копейках" - с точки зрения модели предметной области. То есть, в программе хранится тоже так;</s>

<s>7. Пока не поддержана функциональность "изменение цены товара".</s> **Upd.** Выделите, пожалуйста, повторяющуюся логику (например, чекер ограничителей цены) в служебный метод с заменой всех повторов на вызовы этого метода: правой кнопкой мыши по выделенному фрагменту кода -> Refactor -> Extract method...

**Comment by mishkowsky** [comment]
"Выделение интерфейса" — имеется ввиду выделение в отдельный файл или какими-то отступами внутри кода?

Checked исключения проверяются компилятором до работы кода, unchecked исключения компилятор не ожидает, они могут возникнуть в процессе работы кода.

Objects.hash был выбран, потому что Вы про него упомянули. Почитал про него подробнее, заменил на собственную реализацию.

Функциональность "изменение цены товара" поддержана методом changePrice в классе Product.

**Comment by Suntrie** [comment]
"Выделение интерфейса" - это то, что Вы отдельно описали контракт на то, какие методы должен поставлять библиотечный класс (interface ListOfProducts). Если клиентский код будет использовать, например, через объявление в своих методах (или полях) что-то вроде public void clientFunc(ListOfProducts listOfProducts), то переезд на новый класс, имплементящий этот интерфейс, обойдётся сравнительно более дешево, чем если бы Вы указывали конкретную реализацию и методы, специфичные для нее.

**Comment by Suntrie** [comment]
<s>Поясните, пожалуйста, к какому из классов исключений относится IllegalArgumentException и почему Вы выбрали его (должна ли быть у программиста-клиента возможность обработки исключения)?</s>

**Comment by Suntrie** [comment]
<s>Самое простое, что можно сделать с хэш-кодом и equals - это автосгенерировать их (Code -> generate...). В большинстве случаев, этого будет достаточно.</s>

**Comment by mishkowsky** [comment]
IllegalArgumentException относится к RuntimeException (unchecked). Это исключение было выбрано, потому что у нас нет гарантий на правильность входных данных. Думаю да, у программиста-клиента должна быть возможность обработки исключения.

**Comment by Suntrie** [comment]
Обсудили, что это не совсем так.
